### ISSUE TITLE
'unitdata' import fail for 'charmhelpers.core.hookenv' package

### ISSUE THREAD

**Issue by mrcdb** [AdamIsrael/layer-sshproxy#3]
Hello,

I am unable to run the the lastest build of the `sshproxy` in Juju repository (within an Open Source MANO deployment) because of the following import error:

```
File
"/var/lib/juju/agents/unit-flfh-test-gui-flhfilter-b-0/charm/reactive/sshproxy.py",
line 18, in <module>
from charmhelpers.core.hookenv import (
  ImportError: cannot import name 'unitdata'
```

From the `charm-helpers` github repo, I see that `unitdata` is available under the `charmhelpers.core` package, not the `charmhelpers.core.hookenv` one [1].  Also, if I manually import the `unitdata` file from `charmhelpers.core ` in a Python interactive shell, it works (while the `*.hookenv` version doesn't).

Do you have any suggestion about how to solve this issue?

[1] https://github.com/juju/charm-helpers/blob/master/charmhelpers/core/unitdata.py

**Comment by AdamIsrael** [comment]
This should be fixed now. There were some changes in flight to support metrics collection.
