### ISSUE TITLE
Missing "import traceback" in sshproxy.py

### ISSUE THREAD

**Issue by dreibh** [AdamIsrael/layer-sshproxy#6]
sshproxy.py lacks an "import traceback". When something goes wrong in verify_ssh_credentials(), the call to traceback.format_exc() leads to an exception.

Example:
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed Traceback (most recent call last):
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "/var/lib/juju/agents/unit-simulamet-oai-epc-b-spgw-c-aa-0/charm/hooks/config-changed", line 22, in <module>
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     main()
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 74, in main
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     bus.dispatch(restricted=restricted_mode)
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 390, in dispatch
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     _invoke(other_handlers)
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 359, in _invoke
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     handler.invoke()
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 181, in invoke
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     self._action(*args)
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "/var/lib/juju/agents/unit-simulamet-oai-epc-b-spgw-c-aa-0/charm/reactive/sshproxy.py", line 81, in ssh_configured
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     (verified, output) = charms.sshproxy.verify_ssh_credentials()
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed   File "lib/charms/sshproxy.py", line 109, in verify_ssh_credentials
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed     tb = traceback.format_exc()
unit-simulamet-oai-epc-b-spgw-c-aa-0: 12:50:02 DEBUG unit.simulamet-oai-epc-b-spgw-c-aa/0.config-changed NameError: name 'traceback' is not defined

**Comment by dreibh** [comment]
I just noticed the pull request here: https://github.com/AdamIsrael/layer-sshproxy/pull/5 . It contains the missing import.

**Comment by AdamIsrael** [comment]
This is fixed, as noted, by pull request #5.
